package com.example.express.security;

import lombok.Getter;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.User;

import java.util.Collection;

@Getter // Use Lombok to generate getters
public class CustomUserDetails extends User {

    private final Long id;
    private final String name; // Real name or nickname
    private final Long storeId;
    private final String storeName;

    public CustomUserDetails(
            Long id,
            String username,
            String password,
            String name,
            Long storeId,
            String storeName,
            Collection<? extends GrantedAuthority> authorities) {
        super(username, password, authorities);
        this.id = id;
        this.name = name;
        this.storeId = storeId;
        this.storeName = storeName;
    }

    // You can add constructors for User entities as well if needed,
    // passing null or default values for storeId/storeName.
    public CustomUserDetails(
            Long id,
            String username,
            String password,
            String name,
            Collection<? extends GrantedAuthority> authorities) {
        super(username, password, authorities);
        this.id = id;
        this.name = name;
        this.storeId = null; // Or appropriate default
        this.storeName = null; // Or appropriate default
    }

    // Getters are generated by Lombok's @Getter
}
